#! /bin/sh

feh --no-fehbg --bg-fill "$HOME/.config/bspwm/mojave.jpg"
#feh --no-fehbg --bg-fill "$HOME/.config/bspwm/wall.jpg"
xsetroot -cursor_name left_ptr &
sxhkd &
picom &
nm-applet &
#source $HOME/.config/env
bspc monitor -d WEB TTY DB SYS MISC

bspc config border_width         0
bspc config top_padding 	 -15
bspc config right_padding	 -15
bspc config left_padding         -15
bspc config bottom_padding       -15
bspc config window_gap         	 20

#bspc config focused_border_color      "#0C2220"
#bspc config normal_border_color "#0C2220"
#bspc config urgent_border_color "#B58900"
#bspc config presel_border_color "#26E2FF"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

(ps x | grep bspswallow | grep -v grep) || bspswallow &

$HOME/.config/polybar/launch.sh
$HOME/.local/bin/wallblur
